version: '3.8'

services:

  mongo:
    image: mongo:4.0.0
    hostname: mongo
    restart: unless-stopped
    volumes:
      - ./docker/mongo:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) eq 1
      interval: 10s
      start_period: 30s
    command: "--replSet replset"
    ports:
      - 27017:27017
